import Link from "next/link";

import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { ThemeToggle } from "@/components/theme-toggle";

const SECTIONS = [
  {
    heading: "Where it runs",
    body: `One compose file on a single EC2 instance: Postgres, the FastAPI backend, a worker draining the transcription and summarisation queues, and the Next.js frontend.

Nginx is the only door in. It terminates TLS and forwards \`/\` to the frontend on 3000 and \`/api/\` to the backend on 8000; the security group leaves those ports closed and Cloudflare terminates TLS in front of the origin. \`deploy/setup-ec2.sh\` prepares a fresh instance, \`deploy/setup-nginx.sh\` installs the site.

TLS is an infrastructure assumption, never enforced by the app: the app serves HTTP and the proxy terminates it.`,
  },
  {
    heading: "Authentication and ownership",
    body: `Better Auth inside Next.js owns signup, login and sessions against Postgres. Its five tables are generated by its CLI and nothing else touches them; Alembic is configured to ignore exactly those tables.

Each session gets a signed JWT, sent as \`Authorization: Bearer\`. FastAPI verifies the Ed25519 signature against Better Auth's JWKS and accepts nothing else: no passwords, no session table, no login endpoint.

Every query is scoped to the verified subject, so one account can never see another's notes — a request for somebody else's note returns 404, not 403. A missing or forged token is 401. \`ENABLE_DEV_AUTH\` exists for local development only, and the app refuses to start with it set in production.

Playback works around one browser limit: an audio element cannot send an Authorization header. So an authenticated API route streams the bytes out of R2 and the player gets an object URL, with Range requests preserved for seeking. ADTS AAC and AMR are transcoded to mp3 on the way out because browsers cannot seek them.`,
  },
  {
    heading: "Upload to transcript",
    body: `The browser streams audio as multipart form data — never through a server action, which would buffer the body and block the request. The backend validates the file, stores it under a generated key, inserts a queued row and returns 201. Nothing waits on speech recognition.

A worker claims the note and runs Gnani's Batch STT sequence: create, start, poll no tighter than ten seconds to a terminal status, list files, download the transcript URL. Batch takes whole files up to four hours, so nothing is ever chunked — chunking would only add mid-word splice artefacts.

Gnani's Batch API deserves the praise: the create → start → poll → files → download sequence is explicit, terminal statuses are honest, and auth is one header. The download already carries per-segment timestamps, so every pass stores them and the transcript renders as timestamped lines — clicking one jumps the player there. Still unexplored on our side: the metrics section for job observability, the live transcription path for realtime use, and smarter polling intervals per job size.

The client polls the note endpoint while the status is non-terminal. Polling is the only source of progress truth: no websockets, no server-sent events.`,
  },
  {
    heading: "Where files live",
    body: `Audio lives in Cloudflare R2 and nowhere else: not in Postgres, not in the repo, not on disk. The row holds the object key, size, content type and duration; \`src/storage.py\` is the only module that builds a key or holds bucket credentials.

The bucket is private with no public URL. The API streams bytes to the browser with Range support: no cross-origin grant, no expiring link, no re-signed URL restarting the player on every poll.

Gnani can fetch source audio from a bucket itself, but only from \`aws_s3\`, \`gcp_gcs\` and \`azure_blob\`. R2 is accepted as \`aws_s3\` and then fails the fetch with \`START_FAILED\`, so the worker downloads the object once to a temp file and uploads the bytes instead. The cost is Gnani's 10MB per-file cap, which the upload limit already matches.`,
  },
  {
    heading: "Synchronous vs background",
    body: `A request does three things: verify the session, validate and store the file, write the row. Transcription takes minutes, so it runs in a worker.

The queue is Postgres, so deferring a job is one insert and claiming one is a row lock. No Redis, no Kafka: at this volume a third stateful service costs more to operate than it saves. If the API dies between committing the row and enqueueing the job, a sweep on worker start re-enqueues the orphan.

Past a volume where one process is the bottleneck, the honest upgrades are Celery with Redis for task fan-out and Kafka for event streaming — adopted when queue depth says so, not before.`,
  },
  {
    heading: "Failure and progress",
    body: `Every state transition hits the database before the work starts, so a dead worker leaves an explainable state, never a stuck spinner. One worker holds a note at a time, proven by a lease it keeps renewing; a sweep every minute returns notes with no live lease to queued.

Nothing retries automatically after a provider call, because a retry would re-bill audio already paid for. The provider job id is recorded instead, so the next attempt resumes that job. Only an explicit Retry submits fresh — and only the failed step: transcription again, or the summary alone when the transcript already exists. Every pass is kept in transcript_iterations, so a failed attempt stays visible in history without destroying what already worked.`,
  },
  {
    heading: "What I would change with more time",
    body: `Observability first: Prometheus metrics on the API and workers with Grafana dashboards, because at this volume the interesting failures are timeouts and rate limits, not throughput. Then transcripts paginated for display, two-speaker diarization exposed, and editable transcripts and summaries. Live transcription from the microphone rather than the batch path. Gujarati and Punjabi are rejected at upload because Batch does not support them; that lifts the day the provider ships them.

Backups for Postgres, because the bucket holds the audio but the database holds the only copy of what was said about it. And a second worker once queue depth makes one process the bottleneck.`,
  },
];

export default function ArchitecturePage() {
  return (
    <>
      <header className="flex items-center justify-between border-b border-rule px-4 py-4 sm:px-6">
        <Link className="text-sm font-medium tracking-tight" href="/">
          Audio Notes
        </Link>
        <div className="flex items-center gap-6">
          <ThemeToggle />
          <span className="micro">Architecture</span>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-4 py-8 sm:px-6 sm:py-12">
        <h1 className="max-w-xl text-3xl leading-tight font-medium tracking-tight">
          How the system works, end to end.
        </h1>
        <p className="micro mt-4">
          Next.js · FastAPI · Postgres · R2 · Gnani Batch STT · GroqCloud · one EC2 instance
        </p>

        <section className="border-t border-rule py-8">
          <h2 className="micro">The shape of it</h2>
          <ArchitectureDiagram />
        </section>

        <div className="mt-0">
          {SECTIONS.map((section) => (
            <section className="border-t border-rule py-8" key={section.heading}>
              <h2 className="micro">{section.heading}</h2>
              <p className="mt-3 text-[15px] leading-relaxed whitespace-pre-wrap">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </main>
    </>
  );
}