import Link from "next/link";

import { ThemeToggle } from "@/components/theme-toggle";

const SECTIONS = [
  {
    heading: "Where it runs",
    body: `One compose file on a single AWS EC2 instance: Postgres, the FastAPI backend, a worker that drains the transcription and summarisation queues, and the Next.js frontend. The API is a resource server and the frontend is the only thing that talks to a browser, so nothing else is exposed to the internet.

Nginx is the only door in. It terminates TLS and forwards \`/\` to the frontend on 3000 and \`/api/\` to the backend on 8000; the compose file publishes those ports for local debugging only, and the security group leaves them closed. \`deploy/setup-nginx.sh\` installs the site and \`deploy/setup-ec2.sh\` prepares a fresh instance. Cloudflare terminates TLS in front of the origin, so the certificate nginx serves is a Cloudflare origin certificate rather than a public one.

In development the frontend runs on the host with \`bun dev\` on port 3000 and the API on 8000, because container-to-container traffic is not available in every environment.

TLS is an infrastructure assumption, not something the application enforces: the app serves HTTP and the reverse proxy terminates it.`,
  },
  {
    heading: "Authentication and ownership",
    body: `Better Auth runs inside Next.js and owns signup, login and sessions against Postgres. Its five tables — user, session, account, verification and jwks — are generated by the Better Auth CLI and nothing else touches them; Alembic is configured to ignore exactly those tables so autogenerate can never drop another generator's columns.

The JWT plugin issues a signed token per session. The browser sends it as \`Authorization: Bearer\`, and FastAPI verifies the Ed25519 signature against Better Auth's published JWKS, caching keys for five minutes. It accepts nothing else: no password hashing, no session table, no login endpoint.

Every query is scoped to the verified subject, so one account cannot read, rename, delete or play another account's audio — a request for somebody else's note returns 404, not 403, because the existence of the note is itself private. A missing or forged token is 401. There is a development bypass behind \`ENABLE_DEV_AUTH\`, and the app refuses to start if that flag is set while \`ENV=production\`.

One consequence worth stating: an HTML audio element cannot send an Authorization header. So playback never goes through an authenticated proxy — the API returns a presigned R2 URL and the element reads R2 directly, with Range requests intact for seeking.`,
  },
  {
    heading: "Upload to transcript",
    body: `The browser streams the audio to the backend as multipart form data — never through a Next.js server action, which would buffer the whole body and block the request. The backend checks the content type and the size limit, writes the file under a generated key, inserts a notes row with status queued, and returns 201 immediately. Nothing waits on speech recognition.

A worker claims queued notes, writes transcribing before it starts, and submits the file to Gnani's Batch STT API in the documented order: create a job, start it, poll every ten seconds or slower until a terminal status, list the job's files, then download the transcript URL. When the transcript lands the worker writes it and the note becomes ready.

Batch STT rather than the synchronous endpoint because the synchronous one caps audio at sixty seconds and this app must take a two-minute recording. Batch accepts up to four hours per file, so the app sends whole files and never chunks them — chunking would only add mid-word splice artefacts.

The client polls the note endpoint while the status is non-terminal and renders from the status field. Polling is the only source of progress truth: no websockets, no server-sent events.`,
  },
  {
    heading: "Where files live",
    body: `Audio lives in Cloudflare R2, never in the database, never in the repo, and never on the instance's disk. The notes row holds the object key, size, content type and duration; \`src/storage.py\` is the only module that builds a key or holds bucket credentials.

The bucket is private. There is no public URL and no custom domain: \`audio_url\` is a presigned GET link that expires after an hour, so a leaked link stops working instead of becoming a permanent public file. Two things use those links — the browser hands one straight to the audio element, and Gnani is handed one as a \`cloud_storage\` source for Batch STT, which is why the ten megabyte multipart cap does not apply. The synchronous endpoint still needs real bytes, so that one path downloads to a temporary file first and releases it before polling starts.

Because the file is served with HTTP range support, seeking works through the native player without any custom streaming code.`,
  },
  {
    heading: "Synchronous vs background",
    body: `Only three things happen in the request: verifying the session, validating and storing the file, and writing the row. Transcription runs in a worker, because a single transcription takes minutes — far longer than a request should hold a connection.

The queue is Postgres-backed, so the API defers a job by inserting a row and the worker claims it with a lock. No Redis, no Kafka: at this volume a third stateful service would be more to operate than it is worth. If the API dies between committing the note and enqueueing the job, a sweep on worker start re-enqueues any queued note that has no job.

Retries with backoff are bounded. After the last attempt the note becomes failed with the provider's reason attached, instead of hanging in queued forever.`,
  },
  {
    heading: "Failure and progress",
    body: `A note is always in exactly one of four states — queued, transcribing, ready, failed — and every transition is written to the database before the work begins, so a crashed worker leaves a truthful state rather than a spinner that never resolves. Failed notes store a code and a message, and the interface shows that message rather than a generic failure.

Language selection is validated at upload rather than at job time. Gnani's Batch API supports eight of the ten Indian languages; Gujarati and Punjabi work on the synchronous endpoint only, so picking them at upload returns a clear 400 instead of queueing work that is guaranteed to fail.

Health is split in two: a liveness endpoint that never touches Postgres, storage or Gnani, so a dependency blip does not make Docker restart a healthy API, and readiness for everything else.`,
  },
  {
    heading: "What is not built yet",
    body: `Two things are stubs, and the interface says so rather than pretending otherwise. Transcription returns no transcript yet: the worker, the queue and the Gnani client are the next unit, and a note sits at queued until then. Summarisation is not implemented at all — the summary field exists and stays null, and the transcript is the fallback view.

Everything else in this document describes code that runs today.`,
  },
  {
    heading: "What I would change with more time",
    body: `Transcripts would be paginated or virtualised for display so a long recording does not render as one enormous block, and diarization would be exposed for two-speaker recordings. Transcripts and summaries would be editable, because a transcription is a starting point rather than a verdict.

On the operations side: request metrics and a queue dashboard before any tuning, because at this volume the interesting failures are timeouts and rate limits rather than throughput. Backups for Postgres, because the bucket holds audio but the database holds the only copy of what was said about it. And a second worker once the queue depth makes one process the bottleneck.`,
  },
];

export default function ArchitecturePage() {
  return (
    <>
      <header className="flex items-center justify-between border-b border-rule px-6 py-4">
        <Link className="text-sm font-medium tracking-tight" href="/">
          Audio Notes
        </Link>
        <div className="flex items-center gap-6">
          <ThemeToggle />
          <span className="micro">Architecture</span>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-12">
        <h1 className="max-w-xl text-3xl leading-tight font-medium tracking-tight">
          How the system works, end to end.
        </h1>
        <p className="micro mt-4">
          Next.js · FastAPI · Postgres · Gnani Batch STT
        </p>

        <div className="mt-12">
          {SECTIONS.map((section) => (
            <section className="border-t border-rule py-8" key={section.heading}>
              <h2 className="micro">{section.heading}</h2>
              <p className="mt-3 text-[15px] leading-relaxed whitespace-pre-wrap">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </main>
    </>
  );
}