import Link from "next/link";

import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { ThemeToggle } from "@/components/theme-toggle";

const SECTIONS = [
  {
    heading: "Where it runs",
    body: `One compose file on a single AWS EC2 instance: Postgres, the FastAPI backend, a worker that drains the transcription and summarisation queues, and the Next.js frontend. The API is a resource server and the frontend is the only thing that talks to a browser, so nothing else is exposed to the internet.

Nginx is the only door in. It terminates TLS and forwards \`/\` to the frontend on 3000 and \`/api/\` to the backend on 8000; the compose file publishes those ports for local debugging only, and the security group leaves them closed. \`deploy/setup-nginx.sh\` installs the site and \`deploy/setup-ec2.sh\` prepares a fresh instance. Cloudflare terminates TLS in front of the origin, so the certificate nginx serves is a Cloudflare origin certificate rather than a public one.

In development the frontend runs on the host with \`bun dev\` on port 3000 and the API on 8000, because container-to-container traffic is not available in every environment.

TLS is an infrastructure assumption, not something the application enforces: the app serves HTTP and the reverse proxy terminates it.`,
  },
  {
    heading: "Authentication and ownership",
    body: `Better Auth runs inside Next.js and owns signup, login and sessions against Postgres. Its five tables — user, session, account, verification and jwks — are generated by the Better Auth CLI and nothing else touches them; Alembic is configured to ignore exactly those tables so autogenerate can never drop another generator's columns.

The JWT plugin issues a signed token per session. The browser sends it as \`Authorization: Bearer\`, and FastAPI verifies the Ed25519 signature against Better Auth's published JWKS, caching keys for five minutes. It accepts nothing else: no password hashing, no session table, no login endpoint.

Every query is scoped to the verified subject, so one account cannot read, rename, delete or play another account's audio — a request for somebody else's note returns 404, not 403, because the existence of the note is itself private. A missing or forged token is 401. There is a development bypass behind \`ENABLE_DEV_AUTH\`, and the app refuses to start if that flag is set while \`ENV=production\`.

One consequence worth stating: an HTML audio element cannot send an Authorization header. So playback bytes flow through an authenticated API route that streams them out of R2, and the player gets them as an object URL — Range requests are preserved for seeking, and nothing in the browser holds a credential-bearing URL. Accessible formats serve directly; raw ADTS AAC and AMR are transcoded to mp3 on the way out because browsers cannot seek or report a real duration for them.`,
  },
  {
    heading: "Upload to transcript",
    body: `The browser streams the audio to the backend as multipart form data — never through a Next.js server action, which would buffer the whole body and block the request. The backend checks the content type and the size limit, writes the file under a generated key, inserts a notes row with status queued, and returns 201 immediately. Nothing waits on speech recognition.

A worker claims queued notes, writes transcribing before it starts, and submits the file to Gnani's Batch STT API in the documented order: create a job, start it, poll every ten seconds or slower until a terminal status, list the job's files, then download the transcript URL. When the transcript lands the worker writes it and the note becomes ready.

Batch STT rather than the synchronous endpoint because the synchronous one caps audio at sixty seconds and this app must take a two-minute recording. Batch accepts up to four hours per file, so the app sends whole files and never chunks them — chunking would only add mid-word splice artefacts.

The client polls the note endpoint while the status is non-terminal and renders from the status field. Polling is the only source of progress truth: no websockets, no server-sent events.`,
  },
  {
    heading: "Where files live",
    body: `Audio lives in Cloudflare R2 and nowhere else: not in Postgres, not in the repo, not on the instance's disk. The notes row holds the object key, size, content type and duration. \`src/storage.py\` is the only module that builds a key or holds bucket credentials.

The bucket is private, with no public URL and no custom domain. The API streams the bytes to the browser with Range support, which costs one hop and buys three things: no cross-origin grant to configure, no link that expires in the middle of a long recording, and no fresh signature on every poll restarting the player's buffer.

Gnani's Batch API can fetch from a bucket itself, but only from \`aws_s3\`, \`gcp_gcs\` and \`azure_blob\`. R2 is accepted as \`aws_s3\` with our endpoint and the job is created, then fails to fetch the object with \`START_FAILED\`. So both Gnani endpoints receive the bytes: the worker downloads the object once into a temporary file, uploads it, and releases the file before it starts polling. The cost is Gnani's 10MB per-file cap, which the upload limit already matches. Moving to a bucket Gnani can read would remove the download and lift the cap.`,
  },
  {
    heading: "Synchronous vs background",
    body: `Only three things happen in the request: verifying the session, validating and storing the file, and writing the row. Transcription runs in a worker, because a single transcription takes minutes — far longer than a request should hold a connection.

The queue is Postgres-backed, so the API defers a job by inserting a row and the worker claims it with a lock. No Redis, no Kafka: at this volume a third stateful service would be more to operate than it is worth. If the API dies between committing the note and enqueueing the job, a sweep on worker start re-enqueues any queued note that has no job.

Retries with backoff are bounded. After the last attempt the note becomes failed with the provider's reason attached, instead of hanging in queued forever.`,
  },
  {
    heading: "Failure and progress",
    body: `Every state transition is written to the database before the work begins, so a worker that dies leaves a state the UI can explain rather than a spinner that never resolves. A note is only ever held by one worker, proven by a lease that the running job keeps pushing forward.

A lease is not enough on its own. The worker sweeps for abandoned notes every minute, not only at startup, because a crash long after boot would otherwise leave a note waiting for the next restart. A note in a non-terminal state with no live lease goes back to queued and is re-deferred.

Nothing retries automatically after a provider call, because a retry would re-send audio that has already been billed. Instead the provider job id is recorded, so the next attempt resumes that job instead of paying twice. If it turns out to be dead, one fresh submission replaces it — and that only happens because somebody asked.

Asking is a button. Retry re-runs only the step that failed: transcription again for a failed note, the summary alone when the transcript already exists. Every pass is kept in the transcript_iterations table and the note shows the latest one, so a failed attempt is visible in history without destroying a transcript that already worked.`,
  },
  {
    heading: "What I would change with more time",
    body: `Transcripts would be paginated or virtualised for display so a long recording does not render as one enormous block, and diarization would be exposed for two-speaker recordings. Transcripts and summaries would be editable, because a transcription is a starting point rather than a verdict. A few small features are easy wins on top: live transcription from the recording itself rather than the batch path, and segment-level time indexing so a transcript line can jump the player to that moment. Gujarati (gu-IN) and Punjabi (pa-IN) are rejected at upload today because Gnani Batch does not support them; adding polling-backed batch support for both is a small feature once the provider exposes them.

On the operations side: request metrics and a queue dashboard before any tuning, because at this volume the interesting failures are timeouts and rate limits rather than throughput. Backups for Postgres, because the bucket holds audio but the database holds the only copy of what was said about it. And a second worker once the queue depth makes one process the bottleneck.`,
  },
];

export default function ArchitecturePage() {
  return (
    <>
      <header className="flex items-center justify-between border-b border-rule px-4 py-4 sm:px-6">
        <Link className="text-sm font-medium tracking-tight" href="/">
          Audio Notes
        </Link>
        <div className="flex items-center gap-6">
          <ThemeToggle />
          <span className="micro">Architecture</span>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-4 py-8 sm:px-6 sm:py-12">
        <h1 className="max-w-xl text-3xl leading-tight font-medium tracking-tight">
          How the system works, end to end.
        </h1>
        <p className="micro mt-4">
          Next.js · FastAPI · Postgres · R2 · Gnani Batch STT · GroqCloud · one EC2 instance
        </p>

        <section className="border-t border-rule py-8">
          <h2 className="micro">The shape of it</h2>
          <ArchitectureDiagram />
        </section>

        <div className="mt-0">
          {SECTIONS.map((section) => (
            <section className="border-t border-rule py-8" key={section.heading}>
              <h2 className="micro">{section.heading}</h2>
              <p className="mt-3 text-[15px] leading-relaxed whitespace-pre-wrap">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </main>
    </>
  );
}