"""transcript iterations

Revision ID: 3141d5041ad4
Revises: 9b1df34aaca1
Create Date: 2026-10-03 22:51:47.611527
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3141d5041ad4'
down_revision: str | None = '9b1df34aaca1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_iterations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_iterations_note_id'), 'transcript_iterations', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_iterations_note_id'), table_name='transcript_iterations')
    op.drop_table('transcript_iterations')
    # ### end Alembic commands ###
