"""worker lease and provider bookkeeping

Revision ID: 9b1df34aaca1
Revises: c0ad65378721
Create Date: 2026-10-03 19:44:19.113808
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9b1df34aaca1'
down_revision: str | None = 'c0ad65378721'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('attempt_id', sa.UUID(), nullable=True))
    op.add_column('notes', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('provider_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('provider_job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'provider_job_id')
    op.drop_column('notes', 'provider_submitted_at')
    op.drop_column('notes', 'lease_expires_at')
    op.drop_column('notes', 'attempt_id')
    # ### end Alembic commands ###
