"""add segments to notes and transcript_iterations

Revision ID: dfc0132a5f9b
Revises: 3141d5041ad4
Create Date: 2026-10-04 04:22:08.154460
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dfc0132a5f9b'
down_revision: str | None = '3141d5041ad4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('segments', sa.JSON(), nullable=True))
    op.add_column('transcript_iterations', sa.Column('segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_iterations', 'segments')
    op.drop_column('notes', 'segments')
    # ### end Alembic commands ###
